jobs:
  build-package:
    docker:
      - image: circleci/golang:1.15
    resource_class: small
    working_directory: /go/src/github.com/ThelonKarrde/CommentCI
    steps:
      - checkout
      - run:
          name: Get go packages
          command: |
            go get -d -v -u all
      - run:
          name: Build package
          command: |
            go build -tags netgo -a -o /go/bin/commentci ./cmd/CommentCI.go
      - run:
          name: Run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...

  deploy-to-github:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/ThelonKarrde/CommentCI
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run:
          name: cross compile
          command: |
            gox -os="linux darwin windows" -arch="amd64" -output="dist/commentci{{.OS}}_{{.Arch}}"
            cd dist/ && gzip *
      - add_ssh_keys:
          fingerprints:
            - "65:ab:62:56:f6:68:e7:22:96:9b:d6:c6:62:ad:03:8d"
      - run:
          name: create release
          command: |
            tag=$(semantics --output-tag)
            if [ "$tag" ]; then
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag dist/
            else
              echo "The commit message(s) did not indicate a major/minor/patch version."
            fi

  build-docker:
    docker:
      - image: docker:20.10.3-git
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t commentci .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_TOKEN
              docker tag commentci "rivshiell/commentci:${CIRCLE_TAG}"
              docker push "rivshiell/commentci:${CIRCLE_TAG}"
            fi
workflows:
  version: 2
  comment-ci:
    jobs:
      - build-docker:
          context:
            - docker-hub
      - build-package
      - deploy-to-github:
          context:
            - github-access
          requires:
            - build-package
          filters:
            branches:
              only: master